### PR TITLE
Test functions

### PR DESCRIPTION
**Pull request by Prasanthkota165**
Without a pull request don't push anything. Thanks

### CODE REVIEW

**Comment by Prasanthkota165** [comment]
Why we need \ character in the readme file. We got a conflict here which can be resolved. I am suggesting to remove the \ character for the new line in the readme file. Because it is a readme.md not the .c file to catch the new line.

**Review by Mathieufalardeau3 — APPROVED** [review]
Good to go

**Comment by rishithrao57** [comment]
I tested everything in Ubuntu and everything works perfectly. We can merge it.

**Comment by Mathieufalardeau3** [comment]
> 
> 
> I tested everything in Ubuntu and everything works perfectly. We can merge it.

Did you try the "make allrun" command?

**Comment by rishithrao57** [comment]
Yes I did. It worked without showing any errors.

**Review by rishithrao57 — APPROVED** [review]

**Review by gabriels2018 — APPROVED** [review]
I approve the merge to the master branch

**Review by Mathieufalardeau3 — APPROVED** [review]

**Review by rishithrao57 — APPROVED** [review]

**Review by gabriels2018 — APPROVED** [review]
I approve merging these changes

**Comment by Prasanthkota165** [comment]
Everything looks good to me in linux. I approve these changes to merge into master.

**Pull request merged**
