### PR TITLE
Sudoku output

### LINKED ISSUE #4: outputSudoku
This function is to create the files from the Sudoku puzzle and solution.

### PR DESCRIPTION
**Pull request by Mathieufalardeau3**
Ready for review.

I did not comment my functions in the header file yet. Will add the comments after the pull request is good.

### CODE REVIEW

**Comment by Prasanthkota165** [comment]
Conflict in the files. 
1.include/sudoku.h
2. src/sudoku_base.c
Needed to be manually resolve the conflicts and we can review it.

**Comment by Mathieufalardeau3** [comment]
> 
> 
> Conflict in the files.
> 1.include/sudoku.h
> 2. src/sudoku_base.c
> Needed to be manually resolve the conflicts and we can review it.

Conflicts resolved

**Review by Prasanthkota165 — CHANGES_REQUESTED** [review]
Looks good to me.
But, we already created the bin_folder,build_folder,results_folder in the makefil. No need to create them again . We need to just copy the outputs to the folders. Also, update after line 15, # rest of the makefile

**Comment by Mathieufalardeau3** [comment]
> 
> 
> Looks good to me.
> But, we already created the bin_folder,build_folder,results_folder in the makefil. No need to create them again . We need to just copy the outputs to the folders. Also, update after line 15, # rest of the makefile

I have commented the rest of the file after line #15. 
The create created the bin_folder,build_folder,output_folder is required in the event that somebody accidentally deletes them. It doesn't hurt to leave them in the Makefile

**Review by Prasanthkota165 — APPROVED** [review]

**Comment by gabriels2018** [comment]
Look very good
I think
Most of the include directives that are on top should go to the .h file
About using the directive # inside your function, If I am not mistaken # declarations are placed inside the .h file usually.

**Comment by Mathieufalardeau3** [comment]
@gabriels2018 You should not have closed the pull request. @rishithrao57 still needs to review it. Please just approve the pull request.

**Review by rishithrao57 — APPROVED** [review]
Looks good to me. Thanks.

**Review by gabriels2018 — COMMENTED** [review]
The make file looks very good eventually we will add all the source file there
about the output_sudoku.c we should put the include directives that are on top to the .h file
About using the directive # inside your function, I thought # declarations are placed inside the .h file

**Comment by Mathieufalardeau3** [comment]
> 
> 
> The make file looks very good eventually we will add all the source file there
> about the output_sudoku.c we should put the include directives that are on top to the .h file
> About using the directive # inside your function, I thought # declarations are placed inside the .h file



> 
> 
> The make file looks very good eventually we will add all the source file there
> about the output_sudoku.c we should put the include directives that are on top to the .h file
> About using the directive # inside your function, I thought # declarations are placed inside the .h file

Agree concerning the include directives, but I don't know what you guys are using so I had to put them in the output_sudoku.c file. We can move them to the sudoku.h file on Tuesday. 

About the # inside the function, the reason why is that I don't know which OS the user will be using (LINUX or Windows). The file path needs to be determined at the pre-processing level. It can't be put in the header file because the variable is local, not global. As such, the # declaration for file path are ok.

**Review by gabriels2018 — APPROVED** [review]
It Looks good
We could discuss more about the makefile part on Tuesday

**Comment by Mathieufalardeau3** [comment]
> 
> 
> It Looks good
> We could discuss more about the makefile part on Tuesday

for sure
Are we good with merging the branches?

**Comment by gabriels2018** [comment]
Very good

**Pull request merged**
