### PR TITLE
Initial Readme File

### PR DESCRIPTION
**Pull request by Prasanthkota165**
This is a Initial Readme file. 
Requested for Merging with Development Branch

### CODE REVIEW

**Comment by rishithrao57** [comment]
Ok. Looks good for me. We can add more as the project progresses.

**Review by Prasanthkota165 — COMMENTED** [review]
Good point. But, for release 1, We are making the users to input only the number one. For the later releases, we can add this point. Waiting for others to review it.

**Review by gabriels2018 — APPROVED** [review]
I approve merging the changes, it looks good, we will add more points as we progress with the development of the Sudoku Game Generator Software.

**Comment by Prasanthkota165** [comment]
Looks Good to me. I think we can merge it.

**Comment by Mathieufalardeau3** [comment]
I am good with the changes.

**Review by Mathieufalardeau3 — COMMENTED** [review]
Changes will be made to the README file in the future

**Review by Mathieufalardeau3 — COMMENTED** [review]
test

**Review by Mathieufalardeau3 — COMMENTED** [review]
est

**Review by Mathieufalardeau3 — COMMENTED** [review]
ok

**Pull request merged**
