### PR TITLE
Fix Minor Bugs

### PR DESCRIPTION
**Pull request by Prasanthkota165**
I request everyone to review the comments and merge into master.

### CODE REVIEW

**Review by gabriels2018 — APPROVED** [review]
Looks good

**Comment by Prasanthkota165** [comment]
I will be waiting for any other changes to be done for release 1.
If everything looks good, I will give the release.

**Review by rishithrao57 — APPROVED** [review]

**Review by Mathieufalardeau3 — APPROVED** [review]

**Comment by Prasanthkota165** [comment]
Everything good in testing in linux.  I hope we can merge them.

**Review by rishithrao57 — APPROVED** [review]
Thanks for that change Mathieu. Didn't see that.

**Review by gabriels2018 — APPROVED** [review]

**Pull request merged**
